version: '3'
services:
  db:
    container_name: postgres_ies_2
    image: postgres
    environment:
      POSTGRES_DB: pocket
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    expose:
      - 5432
    ports:
    - "5432:5432"
    restart: always

  registration-login:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    expose:
      - 8080
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - db
