version: '3.1'
services:
  postgres_db:
    container_name: postegres_database_ies
    image: postgres
    environment:
      POSTGRES_DB: pocket
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: daniel
    ports:
      - "5433:5432"
    restart: always

  registration-login:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - postgres_db